trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      pip install -r requirements.txt
      pytest tests/
    displayName: 'Run Tests'
